Add ability to set name and description for agent
kayak/puppet-bamboo_agent pull request #1
Opened 2017-02-28 03:42 UTC by cliff-wakefield

When you have many agents it can be important to differentiate between them, you only have the name and description for agent to do this.

The current module didn't allow for these to be set in bamboo-agent.cfg.xml

This change allows them to be set the name is set to the ID generated or specified for the agent while the description can be set, but will default to ID also if not provided.

The changes to bamboo-agent.cfg.xml have to be done using file_line resources as to not override the other values in the file such as agentUuid, agentDefinition, etc.

2017-03-01 15:30 UTC, vibro requested changes

2017-03-01 15:30 UTC, vibro commented on manifests/agent_cfg.pp
> +# Set individual property values in wrapper.conf
This doesn't seem to be the proper description for this module.

2017-03-01 15:30 UTC, vibro commented on manifests/agent_cfg.pp
> +  file_line { "Update description field $path":
The indentation here does not match the rest of the file.

2017-03-02 02:03 UTC, cliff-wakefield commented
Thanks @vibro made the changes you requested, please review again.

2017-03-03 14:55 UTC, merged

2017-03-03 14:57 UTC, chqr commented
@cliff-wakefield Thanks for the merge! Looking forward to trying this feature on our own agents.